import React, { createContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

export const useLanguage = () => {
  const context = React.useContext(LanguageContext);
  if (!context) {
    // Return default context if not wrapped
    return {
      language: 'ro',
      changeLanguage: () => {},
      t: (key) => translations['ro'][key] || key
    };
  }
  return context;
};

export const translations = {
  ro: {
    home: "Acasă",
    programs: "Programe",
    pricing: "Prețuri",
    schedule: "Orar",
    contact: "Contact",
    freeTrial: "O Ședință Gratuită",
    heroTag: "Antrenează-te ca un campion",
    heroTitle: "FORȚĂ. COMUNITATE. REZULTATE.",
    heroSubtitle: "Descoperă potențialul tău maxim într-o comunitate dedicată performanței. CrossFit pentru toate nivelurile de fitness.",
    startNow: "Începe Acum",
    discoverPrograms: "Descoperă Programele",
    discoverThePrograms: "Descoperă Programele",
    aboutUs: "Despre Noi",
    moreThangym: "Mai mult decât un gym",
    aboutDesc: "Suntem o comunitate de oameni pasionați de fitness și performanță. Indiferent de nivelul tău, te ajutăm să-ți atingi obiectivele prin antrenamente generale de CrossFit, haltere și gimnastică, într-o atmosferă motivantă, cu un antrenor mereu lângă tine, gata să te îndrume.",
    intenseTraining: "Antrenamente Intense",
    intenseTrainingDesc: "Antrenamente variate zilnic, care-ți pun la încercare limitele.",
    strongCommunity: "Comunitate Puternică",
    strongCommunityDesc: "Vino alături de oameni motivați, care te susțin la fiecare pas.",
    professionalCoaching: "Coaching Profesionist",
    professionalCoachingDesc: "Antrenori dedicați progresului tău.",
    visibleResults: "Rezultate Vizibile",
    visibleResultsDesc: "Transformări reale și durabile, obținute prin muncă și dedicare.",
    everyoneUnique: "Fiecare persoană este unică",
    everyoneUniqueDesc: "iar programele noastre variate sunt adaptabile oricărui nivel de fitness.",
    crossfitTitle: "CrossFit",
    crossfitDesc: "Antrenamente funcționale de înaltă intensitate, care combină gimnastică, haltere și condiționare.",
    weightlifting: "Haltere",
    weightliftingDesc: "Tehnici de halterofilie olimpică, pentru dezvoltare forței și puterii explozive.",
    gymnastics: "Gimnastică",
    gymnasticsDesc: "Dezvoltă forța relativă, stabilitatea, mobilitatea și flexibilitatea pentru performanță.",
    personalTraining: "Personal Training",
    personalTrainingDesc: "Antrenament 1-la-1 personalizat pentru a-ți atinge obiectivele in ritmul tău.",
    openGym: "Open Gym",
    openGymDesc: "Acces liber la echipamente pentru antrenamente independente.",
    pricingTitle: "Prețuri",
    pricingSubtitle: "Fiecare plan include coaching profesionist și acces la comunitatea noastră.",
    crossfitMemberships: "Abonamente CrossFit",
    dropIn: "Drop In",
    dropInDesc: "Încearcă un antrenament",
    dropInWeek: "Drop In 1 Week",
    dropInWeekDesc: "Încearcă o săptămână completă",
    eightSessions: "8 Ședințe",
    eightSessionsDesc: "2 antrenamente pe săptămână",
    twelveSessions: "12 Ședințe",
    twelveSessionsDesc: "3 antrenamente pe săptămână",
    unlimited: "Nelimitat",
    unlimitedDesc: "Acces complet fără restricții",
    extraServices: "Servicii Extra",
    openGymMembership: "Open Gym",
    openGymMembershipDesc: "Antrenament independent",
    nutrition: "Nutriție",
    nutritionDesc: "Plan alimentar personalizat",
    ptSessions: "Personal Training",
    pt8sessions: "PT 8 Ședințe",
    pt8sessionsDesc: "Antrenament personalizat",
    pt12sessions: "PT 12 Ședințe",
    pt12sessionsDesc: "Transformare completă",
    popular: "Popular",
    startNowBtn: "Începe Acum",
    ron: "RON",
    scheduleTitle: "Orarul Claselor",
    scheduleSubtitle: "Găsește ora potrivită pentru antrenamentul tău.\n\nClase disponibile de dimineața până seara.",
    monday: "Luni",
    tuesday: "Marți",
    wednesday: "Miercuri",
    thursday: "Joi",
    friday: "Vineri",
    saturday: "Sâmbătă",
    sunday: "Duminică",
    closed: "Închis",
    noClasses: "Nu avem clase programate în această zi",
    spotsAvailable: "locuri",
    coach: "Antrenor",
    contactTitle: "Hai să Vorbim",
    contactSubtitle: "Ai întrebări? Vrei să încerci o clasă gratuită?\n\nScrie-ne și te contactăm în cel mai scurt timp.",
    address: "Adresă",
    phone: "Telefon",
    email: "Email",
    schedule_label: "Program",
    fullName: "Nume Complet",
    fullNamePlaceholder: "Ion Popescu",
    emailPlaceholder: "ion@email.com",
    phonePlaceholder: "+40 722 123 456",
    message: "Mesaj",
    messagePlaceholder: "Cu ce te putem ajuta?",
    sendMessage: "Trimite Mesajul",
    sending: "Se trimite..",
    thank: "Mulțumim!",
    thankDesc: "Am primit mesajul tău. Te vom contacta în curând.",
    sendAnother: "Trimite Alt Mesaj",
    follow: "Urmărește-ne",
    location: "Splaiul Unirii 257-259, Sector 3, București",
    phone1: "+40 748 838 767",
    phone2: "+40 740 269 769",
    email_contact: "train@unbrokenspirit.ro",
    hours: "L-V: 07:00 - 20:30",
    hoursSaturday: "S: 09:00 - 11:30",
    hoursSunday: "D: Închis",
    quickLinks: "Link-uri Rapide",
    footerContact: "Contact",
    terms: "Termeni și Condiții",
    privacy: "Politica de Confidențialitate",
    cookiePolicy: "Politica de Cookie",
    gdprPolicy: "Confidențialitate și GDPR",
    anpc: "ANPC",
    copyright: "Toate drepturile rezervate.",
    tagline: "Comunitatea ta de fitness. Antrenamente funcționale de înaltă intensitate pentru rezultate reale.",
  },
  en: {
    home: "Home",
    programs: "Programs",
    pricing: "Pricing",
    schedule: "Schedule",
    contact: "Contact",
    freeTrial: "Book a Free Session",
    heroTag: "Train like a champion",
    heroTitle: "STRENGTH. COMMUNITY. RESULTS.",
    heroSubtitle: "Discover your maximum potential in a community dedicated to performance. CrossFit for all fitness levels.",
    startNow: "Start Now",
    discoverPrograms: "Discover Programs",
    discoverThePrograms: "Discover the Programs",
    aboutUs: "About Us",
    moreThangym: "More than a gym",
    aboutDesc: "We are a community of people passionate about fitness and performance. Regardless of your level, we help you achieve your goals through general CrossFit training, weightlifting and gymnastics, in a motivating atmosphere, with a coach always by your side, ready to guide you.",
    intenseTraining: "High Intensity Training",
    intenseTrainingDesc: "Varied daily workouts that push your limits.",
    strongCommunity: "Strong Community",
    strongCommunityDesc: "Join motivated people who support you at every step.",
    professionalCoaching: "Professional Coaching",
    professionalCoachingDesc: "Coaches dedicated to your progress.",
    visibleResults: "Visible Results",
    visibleResultsDesc: "Real and lasting transformations achieved through hard work and dedication.",
    everyoneUnique: "Every person is unique",
    everyoneUniqueDesc: "and our varied programs are adaptable to any fitness level.",
    crossfitTitle: "CrossFit",
    crossfitDesc: "High-intensity functional workouts combining gymnastics, weightlifting and conditioning.",
    weightlifting: "Weightlifting",
    weightliftingDesc: "Olympic weightlifting techniques for strength and explosive power development.",
    gymnastics: "Gymnastics",
    gymnasticsDesc: "Develop relative strength, stability, mobility and flexibility for performance.",
    personalTraining: "Personal Training",
    personalTrainingDesc: "1-on-1 personalized training to achieve your goals at your own pace.",
    openGym: "Open Gym",
    openGymDesc: "Free access to equipment for independent workouts.",
    pricingTitle: "Pricing",
    pricingSubtitle: "Each plan includes professional coaching and access to our community.",
    crossfitMemberships: "CrossFit Memberships",
    dropIn: "Drop In",
    dropInDesc: "Try a workout",
    dropInWeek: "Drop In 1 Week",
    dropInWeekDesc: "Try a full week",
    eightSessions: "8 Sessions",
    eightSessionsDesc: "2 workouts per week",
    twelveSessions: "12 Sessions",
    twelveSessionsDesc: "3 workouts per week",
    unlimited: "Unlimited",
    unlimitedDesc: "Unlimited access with no restrictions",
    extraServices: "Extra Services",
    openGymMembership: "Open Gym",
    openGymMembershipDesc: "Independent training",
    nutrition: "Nutrition",
    nutritionDesc: "Personalized meal plan",
    ptSessions: "Personal Training",
    pt8sessions: "PT 8 Sessions",
    pt8sessionsDesc: "Personalized training",
    pt12sessions: "PT 12 Sessions",
    pt12sessionsDesc: "Complete transformation",
    popular: "Popular",
    startNowBtn: "Start Now",
    ron: "RON",
    scheduleTitle: "Class Schedule",
    scheduleSubtitle: "Find the right time for your workout. Classes available from morning to evening.",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",
    closed: "Closed",
    noClasses: "We have no classes scheduled for this day",
    spotsAvailable: "spots",
    coach: "Coach",
    contactTitle: "Let's Talk",
    contactSubtitle: "Do you have any questions? Do you want to try a free class? Write to us and we will contact you as soon as possible.",
    address: "Address",
    phone: "Phone",
    email: "Email",
    schedule_label: "Schedule",
    fullName: "Full Name",
    fullNamePlaceholder: "John Doe",
    emailPlaceholder: "john@email.com",
    phonePlaceholder: "+40 722 123 456",
    message: "Message",
    messagePlaceholder: "How can we help?",
    sendMessage: "Send Message",
    sending: "Sending...",
    thank: "Thank You!",
    thankDesc: "We received your message. We will contact you soon.",
    sendAnother: "Send Another Message",
    follow: "Follow Us",
    location: "Splaiul Unirii 257-259, Sector 3, București",
    phone1: "+40 748 838 767",
    phone2: "+40 740 269 769",
    email_contact: "train@unbrokenspirit.ro",
    hours: "Mon-Fri: 07:00 - 20:30",
    hoursSaturday: "Sat: 09:00 - 11:30",
    hoursSunday: "Sun: Closed",
    quickLinks: "Quick Links",
    footerContact: "Contact",
    terms: "Terms & Conditions",
    privacy: "Privacy Policy",
    cookiePolicy: "Cookie Policy",
    gdprPolicy: "Confidentiality & GDPR",
    anpc: "ANPC",
    copyright: "All rights reserved.",
    tagline: "Your fitness community. High-intensity functional training for real results.",
  }
};

export default function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('appLanguage') || 'ro';
    }
    return 'ro';
  });

  const changeLanguage = (lang) => {
    localStorage.setItem('appLanguage', lang);
    setLanguage(lang);
  };

  const t = (key) => {
    return translations[language][key] || translations['ro'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}