import React, { createContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

export const useLanguage = () => {
  const context = React.useContext(LanguageContext);
  if (!context) {
    // Return default context if not wrapped
    return {
      language: 'ro',
      changeLanguage: () => {},
      t: (key) => translations['ro'][key] || key
    };
  }
  return context;
};

export const translations = {
  ro: {
    home: "Acasă",
    startHere: "Începători",
    programs: "Programe",
    pricing: "Prețuri",
    schedule: "Orar",
    contact: "Contact",
    freeTrial: "O Ședință Gratuită",
    heroTag: "Antrenează-te ca un campion",
    heroTitle: "FORȚĂ. COMUNITATE. REZULTATE.",
    heroSubtitle: "Descoperă potențialul tău maxim într-o comunitate dedicată longevității\nși performanței. CrossFit pentru toate nivelurile de fitness.",
    startNow: "Începe Acum",
    discoverPrograms: "Descoperă Programele",
    discoverThePrograms: "Descoperă Programele",
    aboutUs: "Despre Noi",
    moreThangym: "Mai mult decât un gym",
    aboutDesc: "Suntem o comunitate de oameni pasionați de fitness și performanță. Indiferent de nivelul tău, te ajutăm să-ți atingi obiectivele prin antrenamente generale de CrossFit, haltere și gimnastică, într-o atmosferă motivantă, cu un antrenor mereu lângă tine, gata să te îndrume.",
    intenseTraining: "Antrenamente Intense",
    intenseTrainingDesc: "Antrenamente variate zilnic, care-ți pun la încercare limitele.",
    strongCommunity: "Comunitate Puternică",
    strongCommunityDesc: "Vino alături de oameni motivați, care te susțin la fiecare pas.",
    professionalCoaching: "Coaching Profesionist",
    professionalCoachingDesc: "Antrenori dedicați progresului tău.",
    visibleResults: "Rezultate Vizibile",
    visibleResultsDesc: "Transformări reale și durabile, obținute prin muncă și dedicare.",
    everyoneUnique: "Fiecare persoană este unică",
    everyoneUniqueDesc: "iar programele noastre variate sunt adaptabile oricărui nivel de fitness.",
    crossfitTitle: "CrossFit",
    crossfitDesc: "Antrenamente funcționale de înaltă intensitate, care combină gimnastică, haltere și condiționare.",
    weightlifting: "Haltere",
    weightliftingDesc: "Tehnici de halterofilie olimpică, pentru dezvoltare forței și puterii explozive.",
    gymnastics: "Gimnastică",
    gymnasticsDesc: "Dezvoltă forța relativă, stabilitatea, mobilitatea și flexibilitatea pentru performanță.",
    personalTraining: "Personal Training",
    personalTrainingDesc: "Antrenament 1-la-1 personalizat pentru a-ți atinge obiectivele in ritmul tău.",
    openGym: "Open Gym",
    openGymDesc: "Acces liber la echipamente pentru antrenamente independente.",
    pricingTitle: "Prețuri",
    pricingSubtitle: "Fiecare plan include coaching profesionist și acces la comunitatea noastră.",
    crossfitMemberships: "Abonamente CrossFit",
    dropIn: "Drop In",
    dropInDesc: "Încearcă un antrenament",
    dropInWeek: "Drop In 1 Week",
    dropInWeekDesc: "Încearcă o săptămână completă",
    eightSessions: "8 Ședințe",
    eightSessionsDesc: "2 antrenamente pe săptămână",
    twelveSessions: "12 Ședințe",
    twelveSessionsDesc: "3 antrenamente pe săptămână",
    unlimited: "Nelimitat",
    unlimitedDesc: "Acces complet fără restricții",
    extraServices: "Servicii Extra",
    openGymMembership: "Open Gym",
    openGymMembershipDesc: "Antrenament independent",
    nutrition: "Nutriție",
    nutritionDesc: "Plan alimentar personalizat",
    ptSessions: "Personal Training",
    pt8sessions: "PT 8 Ședințe",
    pt8sessionsDesc: "Antrenament personalizat",
    pt12sessions: "PT 12 Ședințe",
    pt12sessionsDesc: "Transformare completă",
    popular: "Popular",
    startNowBtn: "Începe Acum",
    ron: "RON",
    scheduleTitle: "Orarul Claselor",
    scheduleSubtitle: "Găsește ora potrivită pentru antrenamentul tău.\n\nClase disponibile de dimineața până seara.",
    monday: "Luni",
    tuesday: "Marți",
    wednesday: "Miercuri",
    thursday: "Joi",
    friday: "Vineri",
    saturday: "Sâmbătă",
    sunday: "Duminică",
    closed: "Închis",
    noClasses: "Nu avem clase programate în această zi",
    spotsAvailable: "locuri",
    coach: "Antrenor",
    contactTitle: "Hai să vorbim",
    contactTitlePrefix: "Hai să",
    contactTitleHighlight: "vorbim",
    contactSubtitle: "Ai întrebări? Vrei să încerci o clasă gratuită?\n\nScrie-ne și te contactăm în cel mai scurt timp.",
    address: "Adresă",
    phone: "Telefon",
    email: "E-mail",
    schedule_label: "Program",
    fullName: "Nume Complet",
    fullNamePlaceholder: "Ion Popescu",
    emailPlaceholder: "ion@email.com",
    phonePlaceholder: "+40 722 123 456",
    message: "Mesaj",
    messagePlaceholder: "Cu ce te putem ajuta?",
    sendMessage: "Trimite Mesajul",
    sending: "Se trimite..",
    thank: "Mulțumim!",
    thankDesc: "Am primit mesajul tău. Te vom contacta în curând.",
    sendAnother: "Trimite Alt Mesaj",
    follow: "Urmărește-ne",
    location: "Splaiul Unirii 257-259, Sector 3, București",
    locationCity: "Sector 3, București",
    phone1: "+40 748 838 767",
    phone2: "+40 740 269 769",
    email_contact: "train@unbrokenspirit.ro",
    hours: "L-V: 07:00 - 20:30",
    hoursSaturday: "S: 09:00 - 11:30",
    hoursSunday: "D: Închis",
    quickLinks: "Link-uri Rapide",
    footerContact: "Contact",
    terms: "Termeni și Condiții",
    privacy: "Politica de Confidențialitate",
    cookiePolicy: "Politica de Cookie",
    gdprPolicy: "Confidențialitate și GDPR",
    anpc: "ANPC",
    copyright: "Toate drepturile rezervate.",
    tagline: "Comunitatea ta de fitness. Antrenamente funcționale de înaltă intensitate pentru rezultate reale.",
    startHereTitle: "De Unde Să Începi",
    startHereSubtitle: "Ghid complet pentru cei care sunt noi în lumea CrossFit",
    startHerePreview: "CrossFit nu este doar o modalitate de antrenament - este o revoluție în modul în care ne gândim la fitness. Spre deosebire de salele de sport tradiționale, CrossFit combină puterea unei comunități dedicate cu programare profesională și coaching expert.",
    startHereFullText1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    startHereFullText2: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    startHereFullText3: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
  },
  en: {
    home: "Home",
    startHere: "Beginners",
    programs: "Programs",
    pricing: "Pricing",
    schedule: "Schedule",
    contact: "Contact",
    freeTrial: "Book a Free Session",
    heroTag: "Train like a champion",
    heroTitle: "STRENGTH. COMMUNITY. RESULTS.",
    heroSubtitle: "Discover your maximum potential in a longevity and performance driven community. CrossFit for any level of fitness.",
    startNow: "Start Now",
    discoverPrograms: "Discover Programs",
    discoverThePrograms: "Discover the Programs",
    aboutUs: "About Us",
    moreThangym: "More than a gym",
    aboutDesc: "We are a community of people passionate about fitness and performance. Regardless of your level, we help you achieve your goals through general CrossFit training, weightlifting and gymnastics, in a motivating atmosphere, with a coach always by your side, ready to guide you.",
    intenseTraining: "High Intensity Training",
    intenseTrainingDesc: "Varied daily workouts that push your limits.",
    strongCommunity: "Strong Community",
    strongCommunityDesc: "Join motivated people who support you at every step.",
    professionalCoaching: "Professional Coaching",
    professionalCoachingDesc: "Coaches dedicated to your progress.",
    visibleResults: "Visible Results",
    visibleResultsDesc: "Real and lasting transformations achieved through hard work and dedication.",
    everyoneUnique: "Every person is unique",
    everyoneUniqueDesc: "and our varied programs are adaptable to any fitness level.",
    crossfitTitle: "CrossFit",
    crossfitDesc: "High-intensity functional workouts combining gymnastics, weightlifting and conditioning.",
    weightlifting: "Weightlifting",
    weightliftingDesc: "Olympic weightlifting techniques for strength and explosive power development.",
    gymnastics: "Gymnastics",
    gymnasticsDesc: "Develop relative strength, stability, mobility and flexibility for performance.",
    personalTraining: "Personal Training",
    personalTrainingDesc: "1-on-1 personalized training to achieve your goals at your own pace.",
    openGym: "Open Gym",
    openGymDesc: "Free access to equipment for independent workouts.",
    pricingTitle: "Pricing",
    pricingSubtitle: "Each plan includes professional coaching and access to our community.",
    crossfitMemberships: "CrossFit Memberships",
    dropIn: "Drop In",
    dropInDesc: "Try a workout",
    dropInWeek: "Drop In 1 Week",
    dropInWeekDesc: "Try a full week",
    eightSessions: "8 Sessions",
    eightSessionsDesc: "2 workouts per week",
    twelveSessions: "12 Sessions",
    twelveSessionsDesc: "3 workouts per week",
    unlimited: "Unlimited",
    unlimitedDesc: "Unlimited access with no restrictions",
    extraServices: "Extra Services",
    openGymMembership: "Open Gym",
    openGymMembershipDesc: "Independent training",
    nutrition: "Nutrition",
    nutritionDesc: "Personalized meal plan",
    ptSessions: "Personal Training",
    pt8sessions: "PT 8 Sessions",
    pt8sessionsDesc: "Personalized training",
    pt12sessions: "PT 12 Sessions",
    pt12sessionsDesc: "Complete transformation",
    popular: "Popular",
    startNowBtn: "Start Now",
    ron: "RON",
    scheduleTitle: "Class Schedule",
    scheduleSubtitle: "Find the right time for your workout. Classes available from morning to evening.",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",
    closed: "Closed",
    noClasses: "We have no classes scheduled for this day",
    spotsAvailable: "spots",
    coach: "Coach",
    contactTitle: "Let's Talk",
    contactTitlePrefix: "Let's",
    contactTitleHighlight: "Talk",
    contactSubtitle: "Do you have any questions? Do you want to try a free class? Write to us and we will contact you as soon as possible.",
    address: "Address",
    phone: "Phone",
    email: "E-mail",
    schedule_label: "Schedule",
    fullName: "Full Name",
    fullNamePlaceholder: "John Doe",
    emailPlaceholder: "john@email.com",
    phonePlaceholder: "+40 722 123 456",
    message: "Message",
    messagePlaceholder: "How can we help?",
    sendMessage: "Send Message",
    sending: "Sending...",
    thank: "Thank You!",
    thankDesc: "We received your message. We will contact you soon.",
    sendAnother: "Send Another Message",
    follow: "Follow Us",
    location: "Splaiul Unirii 257-259, Sector 3, Bucharest",
    locationCity: "Sector 3, Bucharest",
    phone1: "+40 748 838 767",
    phone2: "+40 740 269 769",
    email_contact: "train@unbrokenspirit.ro",
    hours: "Mon-Fri: 07:00 - 20:30",
    hoursSaturday: "Sat: 09:00 - 11:30",
    hoursSunday: "Sun: Closed",
    quickLinks: "Quick Links",
    footerContact: "Contact",
    terms: "Terms & Conditions",
    privacy: "Privacy Policy",
    cookiePolicy: "Cookie Policy",
    gdprPolicy: "Privacy Policy",
    anpc: "ANPC",
    copyright: "All rights reserved.",
    tagline: "Your fitness community. High-intensity functional training for real results.",
    startHereTitle: "Where to Start",
    startHereSubtitle: "Complete guide for those new to the world of CrossFit",
    startHerePreview: "What is CrossFit? If you searched on the Internet, you probably found the official definition: \"functional movements, constantly varied, executed at high intensity\". Sounds pretty technical, right? Here's what it actually means: CrossFit is a training program designed to prepare you for real life. You're not just training to look good in the mirror (though that will be a consequence). You're training so you can lift a heavy box without throwing your back out, run for the bus without running out of breath, and be in the best physical shape of your life.",
    startHereFullText1: "We combine elements of gymnastics, weightlifting, and cardio, which we change every day. For us, routine is the enemy, so you'll never get bored.\n\n**The Supreme Myth: \"I need to be in shape to start CrossFit\"**\n\nIt's completely normal to feel intimidated the first time, but that's also the biggest barrier keeping you stuck. From the start, one thing needs to be clear: you don't need to be in shape to start CrossFit; you start CrossFit to get in shape.\n\nSaying you need to train before coming to us is like saying you need to already know a foreign language before signing up for a course. It makes no sense!\n\nHere's the reality in our gym: at the same class, you can train side by side with a former competitive athlete and a 40-year-old who works at a desk all day and doesn't have much time for exercise. Both do the same workout, but adapted to each person's level (you'll see below that we call this the scaled version).\n\n• If the workout calls for squats with a heavy barbell, one person might use the prescribed weight, while another might use a PVC pipe or simply their body weight, squatting to a box.\n• If the Workout of the Day includes pull-ups, some will do them on the bar, while others will do assisted pull-ups on the rings with their feet on the ground.\n\nIntensity is completely relative. Coaches are here to make sure you're working correctly and at your own limit of comfort, not your neighbor's. Ego always stays at the door. Come exactly as you are right now.",
    startHereFullText2: "**How Are We Different?**\n\nYou're probably wondering why you'd choose our gym (the box) over a regular gym membership or running in the park. Here's the difference:\n\n**CrossFit vs. Traditional Fitness Gym**\n\n• Your body is the equipment: At a traditional gym, you sit on a chair and push machines that isolate muscle groups. With us, you use free weights (dumbbells, kettlebells, bars) and your own bodyweight to train your entire body simultaneously.\n• Community, not isolation: At a traditional gym, you put in your headphones, avoid eye contact, and are on your own. With us, every class is led by a dedicated coach who teaches and corrects you, and your classmates encourage you exactly when you want to quit.\n• Zero decisions to make: You don't have to think \"what am I working today?\". You come to the gym, the workout is already planned and written on the board, and the coach guides you step by step.\n\n**CrossFit vs. Running (Classic Cardio)**\n\n• Running is excellent for your heart, but it only builds endurance.\n• CrossFit is a complete program. We help you develop all 10 general physical abilities equally: cardiovascular endurance, stamina, strength, flexibility, power, speed, coordination, agility, balance, and accuracy. You become a complete athlete, not just someone who can run a lot.",
    startHereFullText3: "**What Concrete Results Will You Get?**\n\nWe don't sell illusions, but results you can measure in real time, week by week:\n\n• Changed body composition: You'll see a clear decrease in fat percentage and an increase in muscle mass (clothes will fit differently on you).\n• Doubled strength and endurance: You'll be able to lift weights you didn't even dream of on day one and sustain effort longer without getting tired.\n• Iron-clad health: Your blood work will improve (optimal blood pressure, reduced resting heart rate, constant energy throughout the day).\n• Regained mobility: We'll correct poor desk posture and you'll get rid of stiffness and back pain.\n\n**Beginner's Glossary: Speak Our Language**\n\nAt your first workouts, you might hear terms that sound like secret language. Don't worry, here's a mini survival dictionary:\n\n• Box: That's what we call the gym. It's an open, raw space with no mirrors and full of energy.\n• WOD (Workout of the Day): The Workout of the Day. Your mission for that day.\n• AMRAP (As Many Rounds/Reps As Possible): The challenge to do as many rounds or reps as possible from a series of exercises in a given time.\n• EMOM (Every Minute on the Minute): You start an exercise at the beginning of each minute. Whatever time is left in that minute after you finish your reps is your rest.\n• PR / PB (Personal Record / Personal Best): Your personal record on a lift or a WOD. The reason the whole gym will cheer for you!\n• RX (As Prescribed): When you successfully do the workout exactly as written on the board with the prescribed weights and movements.\n• Scaled (Adapted): This is the most important word for you! Any CrossFit movement can be modified (scaled) by the coach to fit your level, whether you're a competitive athlete or sedentary and want to start moving.",
  }
};

export default function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('appLanguage') || 'ro';
    }
    return 'ro';
  });

  const changeLanguage = (lang) => {
    localStorage.setItem('appLanguage', lang);
    setLanguage(lang);
  };

  const t = (key) => {
    return translations[language][key] || translations['ro'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}