import React, { createContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

export const useLanguage = () => {
  const context = React.useContext(LanguageContext);
  if (!context) {
    // Return default context if not wrapped
    return {
      language: 'ro',
      changeLanguage: () => {},
      t: (key) => translations['ro'][key] || key
    };
  }
  return context;
};

export const translations = {
  ro: {
    home: "Acasă",
    startHere: "Începători",
    programs: "Programe",
    pricing: "Prețuri",
    schedule: "Orar",
    contact: "Contact",
    freeTrial: "O Ședință Gratuită",
    heroTag: "Antrenează-te ca un campion",
    heroTitle: "FORȚĂ. COMUNITATE. REZULTATE.",
    heroSubtitle: "Descoperă potențialul tău maxim într-o comunitate dedicată longevității\nși performanței. CrossFit pentru toate nivelurile de fitness.",
    startNow: "Începe Acum",
    discoverPrograms: "Descoperă Programele",
    discoverThePrograms: "Descoperă Programele",
    aboutUs: "Despre Noi",
    moreThangym: "Mai mult decât un gym",
    aboutDesc: "Suntem o comunitate de oameni pasionați de fitness și performanță. Indiferent de nivelul tău, te ajutăm să-ți atingi obiectivele prin antrenamente generale de CrossFit, haltere și gimnastică, într-o atmosferă motivantă, cu un antrenor mereu lângă tine, gata să te îndrume.",
    intenseTraining: "Antrenamente Intense",
    intenseTrainingDesc: "Antrenamente variate zilnic, care-ți pun la încercare limitele.",
    strongCommunity: "Comunitate Puternică",
    strongCommunityDesc: "Vino alături de oameni motivați, care te susțin la fiecare pas.",
    professionalCoaching: "Coaching Profesionist",
    professionalCoachingDesc: "Antrenori dedicați progresului tău.",
    visibleResults: "Rezultate Vizibile",
    visibleResultsDesc: "Transformări reale și durabile, obținute prin muncă și dedicare.",
    everyoneUnique: "Fiecare persoană este unică",
    everyoneUniqueDesc: "iar programele noastre variate sunt adaptabile oricărui nivel de fitness.",
    crossfitTitle: "CrossFit",
    crossfitDesc: "Antrenamente funcționale de înaltă intensitate, care combină gimnastică, haltere și condiționare.",
    weightlifting: "Haltere",
    weightliftingDesc: "Tehnici de halterofilie olimpică, pentru dezvoltare forței și puterii explozive.",
    gymnastics: "Gimnastică",
    gymnasticsDesc: "Dezvoltă forța relativă, stabilitatea, mobilitatea și flexibilitatea pentru performanță.",
    personalTraining: "Personal Training",
    personalTrainingDesc: "Antrenament 1-la-1 personalizat pentru a-ți atinge obiectivele in ritmul tău.",
    openGym: "Open Gym",
    openGymDesc: "Acces liber la echipamente pentru antrenamente independente.",
    pricingTitle: "Prețuri",
    pricingSubtitle: "Fiecare plan include coaching profesionist și acces la comunitatea noastră.",
    crossfitMemberships: "Abonamente CrossFit",
    dropIn: "Drop In",
    dropInDesc: "Încearcă un antrenament",
    dropInWeek: "Drop In 1 Week",
    dropInWeekDesc: "Încearcă o săptămână completă",
    eightSessions: "8 Ședințe",
    eightSessionsDesc: "2 antrenamente pe săptămână",
    twelveSessions: "12 Ședințe",
    twelveSessionsDesc: "3 antrenamente pe săptămână",
    unlimited: "Nelimitat",
    unlimitedDesc: "Acces complet fără restricții",
    extraServices: "Servicii Extra",
    openGymMembership: "Open Gym",
    openGymMembershipDesc: "Antrenament independent",
    nutrition: "Nutriție",
    nutritionDesc: "Plan alimentar personalizat",
    ptSessions: "Personal Training",
    pt8sessions: "PT 8 Ședințe",
    pt8sessionsDesc: "Antrenament personalizat",
    pt12sessions: "PT 12 Ședințe",
    pt12sessionsDesc: "Transformare completă",
    popular: "Popular",
    startNowBtn: "Începe Acum",
    ron: "RON",
    scheduleTitle: "Orarul Claselor",
    scheduleSubtitle: "Găsește ora potrivită pentru antrenamentul tău.\n\nClase disponibile de dimineața până seara.",
    monday: "Luni",
    tuesday: "Marți",
    wednesday: "Miercuri",
    thursday: "Joi",
    friday: "Vineri",
    saturday: "Sâmbătă",
    sunday: "Duminică",
    closed: "Închis",
    noClasses: "Nu avem clase programate în această zi",
    spotsAvailable: "locuri",
    coach: "Antrenor",
    contactTitle: "Hai să vorbim",
    contactTitlePrefix: "Hai să",
    contactTitleHighlight: "vorbim",
    contactSubtitle: "Ai întrebări? Vrei să încerci o clasă gratuită?\n\nScrie-ne și te contactăm în cel mai scurt timp.",
    address: "Adresă",
    phone: "Telefon",
    email: "E-mail",
    schedule_label: "Program",
    fullName: "Nume Complet",
    fullNamePlaceholder: "Ion Popescu",
    emailPlaceholder: "ion@email.com",
    phonePlaceholder: "+40 722 123 456",
    message: "Mesaj",
    messagePlaceholder: "Cu ce te putem ajuta?",
    sendMessage: "Trimite Mesajul",
    sending: "Se trimite..",
    thank: "Mulțumim!",
    thankDesc: "Am primit mesajul tău. Te vom contacta în curând.",
    sendAnother: "Trimite Alt Mesaj",
    follow: "Urmărește-ne",
    location: "Splaiul Unirii 257-259, Sector 3, București",
    locationCity: "Sector 3, București",
    phone1: "+40 748 838 767",
    phone2: "+40 740 269 769",
    email_contact: "train@unbrokenspirit.ro",
    hours: "L-V: 07:00 - 20:30",
    hoursSaturday: "S: 09:00 - 11:30",
    hoursSunday: "D: Închis",
    quickLinks: "Link-uri Rapide",
    footerContact: "Contact",
    terms: "Termeni și Condiții",
    privacy: "Politica de Confidențialitate",
    cookiePolicy: "Politica de Cookie",
    gdprPolicy: "Confidențialitate și GDPR",
    anpc: "ANPC",
    copyright: "Toate drepturile rezervate.",
    tagline: "Comunitatea ta de fitness. Antrenamente funcționale de înaltă intensitate pentru rezultate reale.",
    startHereTitle: "De Unde Să Începi",
    startHereSubtitle: "Ghid complet pentru cei care sunt noi în lumea CrossFit",
    startHerePreview: "Ce este CrossFit-ul? Dacă ai căutat pe Internet, probabil ai găsit definiția oficială: \"mișcări funcționale, constant variate, executate la intensitate ridicată\". Sună cam tehnic, nu? Uite ce înseamnă de fapt: CrossFit-ul este un antrenament conceput să te pregătească pentru viața reală. Nu te antrenezi doar ca să arăți bine în oglindă (deși asta va fi o consecință). Te antrenezi ca să poți ridica o cutie grea fără să ți se blocheze spatele, să alergi după autobuz și să nu rămâi fără aer și să fii în cea mai bună formă fizică a vieții tale.",
    startHereFullText1: "**Mitul suprem: \"Trebuie să fiu deja în formă ca să mă apuc de CrossFit\"**\n\nE perfect normal ca prima oară să te simți intimidat, dar asta e și cea mai mare barieră care te ține pe loc. De la bun început, un lucru trebuie să fie clar: nu trebuie să fii în formă ca să te apuci de CrossFit; te apuci de CrossFit ca să ajungi să fii în formă.\n\nA spune că trebuie să te antrenezi înainte să vii la noi e ca și cum ai spune că trebuie să știi deja o limbă străină înainte să te înscrii la curs. N-are niciun sens!\n\nIată realitatea din sala noastră: la aceeași clasă, se pot antrena cot la cot un fost sportiv de performanță și o persoană de 40 de ani care lucrează toată ziua la birou și nu are prea mult timp pentru mișcare. Amândoi fac același antrenament, dar adaptat nivelului fiecăruia (vei vedea mai jos că noi numim asta varianta scaled).\n\n• Dacă antrenamentul cere genuflexiuni cu o halteră grea, o persoană poate folosi chiar greutatea prescrisă în antrenament, pe când alta poate folosi o țeavă de PVC sau pur și simplu cu greutatea corpulu, așezându-se pe o cutie.\n• Dacă în antrenamentul zilei (Workout of the Day) sunt programate tracțiuni, unii le vor face la bară, iar alții vor face ramat la inele, sprijinindu-se pe picioare.\n\nIntensitatea e complet relativă. Antrenorii sunt aici ca să se asigure că lucrezi corect și la limita ta de confort, nu a celui de lângă tine. Ego-ul rămâne mereu la ușă. Vino exact așa cum ești acum.",
    startHereFullText2: "**Cu ce suntem diferiți?**\n\nProbabil te întrebi de ce ai alege sala noastră (the box) în locul unui abonament la o sală obișnuită sau în locul unei alergări în parc. Iată diferența:\n\n**CrossFit vs. Sala Clasică de Fitness**\n\n• La noi, corpul tău e aparatul: La o sală clasică, te așezi pe un scaun și împingi la niște aparate care izolează grupele musculare. La noi, folosești greutăți libere (gantere, kettlebell, bare) și propria greutate pentru a antrena tot corpul simultan.\n• Comunitate, nu singurătate: La sala clasică, îți pui căștile, eviți contactul vizual și ești pe cont propriu. La noi, fiecare clasă este condusă de un antrenor dedicat care te învață și te corectează, iar colegii te încurajează exact atunci când vrei să renunți.\n• Zero decizii de luat: Nu trebuie să te gândești \"azi ce lucrez?\". Vii la sală, antrenamentul e deja gândit și scris pe tablă, iar antrenorul te ghidează pas cu pas.\n\n**CrossFit vs. Alergarea (Cardio clasic)**\n\n• Alergarea este excelentă pentru inimă, dar lucrează doar rezistența.\n• CrossFitul este un program complet. Noi te ajutăm să dezvolți echilibrat toate cele 10 abilități fizice generale: rezistență cardiovasculară, stamina, forță, flexibilitate, putere, viteză, coordonare, agilitate, echilibru și precizie. Devii un atlet complet, nu doar unul care poate alerga mult.",
    startHereFullText3: "**Ce rezultate concrete vei obține?**\n\nNu vindem iluzii, ci rezultate pe care le poți măsura în timp real, săptămână de săptămână:\n\n• Compoziție corporală schimbată: Vei vedea o scădere clară a procentului de grăsime și o creștere a masei musculare (hainele se vor așeza altfel pe tine).\n• Forță și rezistență dublate: Vei putea ridica greutăți la care nici nu visai în prima zi și vei putea susține efortul mai mult timp, fără să obosești.\n• O sănătate de fier: Analizele tale se vor îmbunătăți (tensiune arterială optimă, ritm cardiac de repaus redus, energie constantă pe tot parcursul zilei).\n• Mobilitate recâștigată: Vom corecta postura greșită de la birou și vei scăpa de rigiditatea și durerile de spate.\n\n**Glosarul Începătorului: Vorbește pe limba noastră**\n\nLa primele antrenamente, s-ar putea să aud termeni care sună a limbaj secret. Stai liniștit, iată mini-dicționarul de supraviețuire:\n\n• Box: Așa numim noi sala. E un spațiu deschis, brut, fără oglinzi și plin de energie.\n• WOD (Workout of the Day): Antrenamentul Zilei. Misiunea ta pentru ziua respectivă.\n• AMRAP (As Many Rounds/Reps As Possible): Provocarea de a face cât mai multe runde sau repetări dintr-o serie de exerciții, într-un timp dat.\n• EMOM (Every Minute on the Minute): Începi un exercițiu fix la începutul fiecărui minut. Ce îți rămâne din acel minut după ce termini repetările este pauza ta.\n• PR / PB (Personal Record / Personal Best): Recordul tău personal la o ridicare sau la un WOD. Motivul pentru care toată sala va bate palma cu tine!\n• RX (As Prescribed): Când reușești să faci antrenamentul exact cu greutățile și mișcările scrise pe tablă.\n• Scaled (Adaptat): Acesta este cel mai important cuvânt pentru tine! Orice mișcare din CrossFit poate fi modificată (scalată) de antrenor pentru a se potrivi nivelului tău, fie că ești sportiv de performanță, fie că ești sedentar și vrei să te apuci de mișcare.",
  },
  en: {
    home: "Home",
    startHere: "Beginners",
    programs: "Programs",
    pricing: "Pricing",
    schedule: "Schedule",
    contact: "Contact",
    freeTrial: "Book a Free Session",
    heroTag: "Train like a champion",
    heroTitle: "STRENGTH. COMMUNITY. RESULTS.",
    heroSubtitle: "Discover your maximum potential in a longevity and performance driven community. CrossFit for any level of fitness.",
    startNow: "Start Now",
    discoverPrograms: "Discover Programs",
    discoverThePrograms: "Discover the Programs",
    aboutUs: "About Us",
    moreThangym: "More than a gym",
    aboutDesc: "We are a community of people passionate about fitness and performance. Regardless of your level, we help you achieve your goals through general CrossFit training, weightlifting and gymnastics, in a motivating atmosphere, with a coach always by your side, ready to guide you.",
    intenseTraining: "High Intensity Training",
    intenseTrainingDesc: "Varied daily workouts that push your limits.",
    strongCommunity: "Strong Community",
    strongCommunityDesc: "Join motivated people who support you at every step.",
    professionalCoaching: "Professional Coaching",
    professionalCoachingDesc: "Coaches dedicated to your progress.",
    visibleResults: "Visible Results",
    visibleResultsDesc: "Real and lasting transformations achieved through hard work and dedication.",
    everyoneUnique: "Every person is unique",
    everyoneUniqueDesc: "and our varied programs are adaptable to any fitness level.",
    crossfitTitle: "CrossFit",
    crossfitDesc: "High-intensity functional workouts combining gymnastics, weightlifting and conditioning.",
    weightlifting: "Weightlifting",
    weightliftingDesc: "Olympic weightlifting techniques for strength and explosive power development.",
    gymnastics: "Gymnastics",
    gymnasticsDesc: "Develop relative strength, stability, mobility and flexibility for performance.",
    personalTraining: "Personal Training",
    personalTrainingDesc: "1-on-1 personalized training to achieve your goals at your own pace.",
    openGym: "Open Gym",
    openGymDesc: "Free access to equipment for independent workouts.",
    pricingTitle: "Pricing",
    pricingSubtitle: "Each plan includes professional coaching and access to our community.",
    crossfitMemberships: "CrossFit Memberships",
    dropIn: "Drop In",
    dropInDesc: "Try a workout",
    dropInWeek: "Drop In 1 Week",
    dropInWeekDesc: "Try a full week",
    eightSessions: "8 Sessions",
    eightSessionsDesc: "2 workouts per week",
    twelveSessions: "12 Sessions",
    twelveSessionsDesc: "3 workouts per week",
    unlimited: "Unlimited",
    unlimitedDesc: "Unlimited access with no restrictions",
    extraServices: "Extra Services",
    openGymMembership: "Open Gym",
    openGymMembershipDesc: "Independent training",
    nutrition: "Nutrition",
    nutritionDesc: "Personalized meal plan",
    ptSessions: "Personal Training",
    pt8sessions: "PT 8 Sessions",
    pt8sessionsDesc: "Personalized training",
    pt12sessions: "PT 12 Sessions",
    pt12sessionsDesc: "Complete transformation",
    popular: "Popular",
    startNowBtn: "Start Now",
    ron: "RON",
    scheduleTitle: "Class Schedule",
    scheduleSubtitle: "Find the right time for your workout. Classes available from morning to evening.",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",
    closed: "Closed",
    noClasses: "We have no classes scheduled for this day",
    spotsAvailable: "spots",
    coach: "Coach",
    contactTitle: "Let's Talk",
    contactTitlePrefix: "Let's",
    contactTitleHighlight: "Talk",
    contactSubtitle: "Do you have any questions? Do you want to try a free class? Write to us and we will contact you as soon as possible.",
    address: "Address",
    phone: "Phone",
    email: "E-mail",
    schedule_label: "Schedule",
    fullName: "Full Name",
    fullNamePlaceholder: "John Doe",
    emailPlaceholder: "john@email.com",
    phonePlaceholder: "+40 722 123 456",
    message: "Message",
    messagePlaceholder: "How can we help?",
    sendMessage: "Send Message",
    sending: "Sending...",
    thank: "Thank You!",
    thankDesc: "We received your message. We will contact you soon.",
    sendAnother: "Send Another Message",
    follow: "Follow Us",
    location: "Splaiul Unirii 257-259, Sector 3, Bucharest",
    locationCity: "Sector 3, Bucharest",
    phone1: "+40 748 838 767",
    phone2: "+40 740 269 769",
    email_contact: "train@unbrokenspirit.ro",
    hours: "Mon-Fri: 07:00 - 20:30",
    hoursSaturday: "Sat: 09:00 - 11:30",
    hoursSunday: "Sun: Closed",
    quickLinks: "Quick Links",
    footerContact: "Contact",
    terms: "Terms & Conditions",
    privacy: "Privacy Policy",
    cookiePolicy: "Cookie Policy",
    gdprPolicy: "Privacy Policy",
    anpc: "ANPC",
    copyright: "All rights reserved.",
    tagline: "Your fitness community. High-intensity functional training for real results.",
    startHereTitle: "Where to Start",
    startHereSubtitle: "Complete guide for those new to the world of CrossFit",
    startHerePreview: "What is CrossFit? If you searched on the Internet, you probably found the official definition: \"functional movements, constantly varied, executed at high intensity\". Sounds pretty technical, right? Here's what it actually means: CrossFit is a training program designed to prepare you for real life. You're not just training to look good in the mirror (though that will be a consequence). You're training so you can lift a heavy box without throwing your back out, run for the bus without running out of breath, and be in the best physical shape of your life.",
    startHereFullText1: "**The Supreme Myth: \"I need to be in shape to start CrossFit\"**\n\nIt's completely normal to feel intimidated the first time, but that's also the biggest barrier keeping you stuck. From the start, one thing needs to be clear: you don't need to be in shape to start CrossFit; you start CrossFit to get in shape.\n\nSaying you need to train before coming to us is like saying you need to already know a foreign language before signing up for a course. It makes no sense!\n\nHere's the reality in our gym: at the same class, you can train side by side with a former competitive athlete and a 40-year-old who works at a desk all day and doesn't have much time for exercise. Both do the same workout, but adapted to each person's level (you'll see below that we call this the scaled version).\n\n• If the workout calls for squats with a heavy barbell, one person might use the prescribed weight, while another might use a PVC pipe or simply their body weight, squatting to a box.\n• If the Workout of the Day includes pull-ups, some will do them on the bar, while others will do assisted pull-ups on the rings with their feet on the ground.\n\nIntensity is completely relative. Coaches are here to make sure you're working correctly and at your own limit of comfort, not your neighbor's. Ego always stays at the door. Come exactly as you are right now.",
    startHereFullText2: "**How Are We Different?**\n\nYou're probably wondering why you'd choose our gym (the box) over a regular gym membership or running in the park. Here's the difference:\n\n**CrossFit vs. Traditional Fitness Gym**\n\n• Your body is the equipment: At a traditional gym, you sit on a chair and push machines that isolate muscle groups. With us, you use free weights (dumbbells, kettlebells, bars) and your own bodyweight to train your entire body simultaneously.\n• Community, not isolation: At a traditional gym, you put in your headphones, avoid eye contact, and are on your own. With us, every class is led by a dedicated coach who teaches and corrects you, and your classmates encourage you exactly when you want to quit.\n• Zero decisions to make: You don't have to think \"what am I working today?\". You come to the gym, the workout is already planned and written on the board, and the coach guides you step by step.\n\n**CrossFit vs. Running (Classic Cardio)**\n\n• Running is excellent for your heart, but it only builds endurance.\n• CrossFit is a complete program. We help you develop all 10 general physical abilities equally: cardiovascular endurance, stamina, strength, flexibility, power, speed, coordination, agility, balance, and accuracy. You become a complete athlete, not just someone who can run a lot.",
    startHereFullText3: "**What Concrete Results Will You Get?**\n\nWe don't sell illusions, but results you can measure in real time, week by week:\n\n• Changed body composition: You'll see a clear decrease in fat percentage and an increase in muscle mass (clothes will fit differently on you).\n• Doubled strength and endurance: You'll be able to lift weights you didn't even dream of on day one and sustain effort longer without getting tired.\n• Iron-clad health: Your blood work will improve (optimal blood pressure, reduced resting heart rate, constant energy throughout the day).\n• Regained mobility: We'll correct poor desk posture and you'll get rid of stiffness and back pain.\n\n**Beginner's Glossary: Speak Our Language**\n\nAt your first workouts, you might hear terms that sound like secret language. Don't worry, here's a mini survival dictionary:\n\n• Box: That's what we call the gym. It's an open, raw space with no mirrors and full of energy.\n• WOD (Workout of the Day): The Workout of the Day. Your mission for that day.\n• AMRAP (As Many Rounds/Reps As Possible): The challenge to do as many rounds or reps as possible from a series of exercises in a given time.\n• EMOM (Every Minute on the Minute): You start an exercise at the beginning of each minute. Whatever time is left in that minute after you finish your reps is your rest.\n• PR / PB (Personal Record / Personal Best): Your personal record on a lift or a WOD. The reason the whole gym will cheer for you!\n• RX (As Prescribed): When you successfully do the workout exactly as written on the board with the prescribed weights and movements.\n• Scaled (Adapted): This is the most important word for you! Any CrossFit movement can be modified (scaled) by the coach to fit your level, whether you're a competitive athlete or sedentary and want to start moving.",
  }
};

export default function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('appLanguage') || 'ro';
    }
    return 'ro';
  });

  const changeLanguage = (lang) => {
    localStorage.setItem('appLanguage', lang);
    setLanguage(lang);
  };

  const t = (key) => {
    return translations[language][key] || translations['ro'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}